addons:
  apt:
    update: true
    packages:
      - google-chrome-stable
      - chromium-chromedriver
rvm:
  - 2.5.1
before_script:
  - gem update bundler
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake
  - bundle exec rake test:system
